### ISSUE TITLE
Possible Images 

### ISSUE THREAD

**Issue by Frankielee2272** [4GeeksAcademy/miami-63-recipe-app#9]
![image](https://github.com/4GeeksAcademy/miami-63-recipe-app/assets/155175699/ffd07c8c-7631-4125-a85e-326fca733207)

![image](https://github.com/4GeeksAcademy/miami-63-recipe-app/assets/155175699/53af57f6-b3a2-49b6-9824-47a2989c734f)

![image](https://github.com/4GeeksAcademy/miami-63-recipe-app/assets/155175699/fa8a4900-2233-456f-883f-f6c9a46112d6)

**Comment by Adnel1** [comment]
We decided to go with a carousel of a set of healthy meal images.
